/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import dao.CozinheiroDAO;
import dao.Conexao;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.cozinheiro;

/**
 *
 * @author Matheus
 */
public class cozinheiroView extends javax.swing.JFrame {

    /** Creates new form categoriaView */
    public cozinheiroView() {
        initComponents();
        try {
            readTable();
        } catch (SQLException ex) {
            Logger.getLogger(cozinheiroView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void readTable() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        Connection conexao = new Conexao().getConnection();
        CozinheiroDAO cozinheirobanco = new CozinheiroDAO(conexao);
        for(cozinheiro p: cozinheirobanco.selectALL()){
            modelo.addRow(new Object[]{
                p.getNome_fantasia(),
                p.getNome_cozinheiro(),
                p.getDt_contrato()
            });
        }
    }
    public void readDesc(String desc) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        Connection conexao = new Conexao().getConnection();
        CozinheiroDAO categoriabanco = new CozinheiroDAO(conexao);
        for(cozinheiro p: categoriabanco.readDesc(desc)){
            modelo.addRow(new Object[]{
                p.getNome_fantasia(),
                p.getNome_cozinheiro(),
                p.getDt_contrato()
            });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldnn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldnF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CADASTRAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ATUALIZAR = new javax.swing.JButton();
        DELETAR = new javax.swing.JButton();
        jTextFieldBusca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonBusca = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnnActionPerformed(evt);
            }
        });

        jLabel1.setText("Data_Contrato");

        jLabel2.setText("Nome Fantasia");

        CADASTRAR.setText("Salvar");
        CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRARActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome_Fantasia", "Nome Cozinheiro", "Data"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );

        ATUALIZAR.setText("Atualizar");
        ATUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATUALIZARActionPerformed(evt);
            }
        });

        DELETAR.setText("Deletar");
        DELETAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETARActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("COZINHEIRO");

        jButtonBusca.setText("Buscar");
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome do Cozinheiro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldnn, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldnF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(CADASTRAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ATUALIZAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DELETAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBusca)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBusca)
                    .addComponent(CADASTRAR)
                    .addComponent(ATUALIZAR)
                    .addComponent(DELETAR))
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRARActionPerformed
        if(jTextFieldnn.getText().isEmpty() || jTextFieldnF.getText().isEmpty() || jTextFieldData.getText().isEmpty() ){
             JOptionPane.showMessageDialog(null,"CAMPO VAZIO");
        }else{
         
            cozinheiro cozinheiro_tela = new cozinheiro(jTextFieldnn.getText(), jTextFieldnF.getText(), jTextFieldData.getText());
        
            try {
                //categoriabanco precisa da conexao com o banco pra inserir
                Connection conexao = new Conexao().getConnection();
                CozinheiroDAO cozinheirobanco = new CozinheiroDAO(conexao);
                boolean existir = cozinheirobanco.validar(cozinheiro_tela);
                if(existir){
                    JOptionPane.showMessageDialog(null,"Cozinheiro ja cadastrado");
                }
                
                cozinheirobanco.insert(cozinheiro_tela);
                JOptionPane.showMessageDialog(null,"Cozinheiro cadastrado com sucesso!!!");
                readTable();
                jTextFieldnF.setText("");
                jTextFieldnn.setText("");
                jTextFieldData.setText("");


            } catch (SQLException ex) {
                Logger.getLogger(cozinheiroView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
        
            
    }//GEN-LAST:event_CADASTRARActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         if(jTable1.getSelectedRow() != -1){
            jTextFieldnF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jTextFieldnn.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextFieldData.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() != -1){
            jTextFieldnF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jTextFieldnn.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextFieldData.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void ATUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATUALIZARActionPerformed
        if(jTextFieldnn.getText().isEmpty() || jTextFieldnF.getText().isEmpty() || jTextFieldData.getText().isEmpty() ){
             JOptionPane.showMessageDialog(null,"CAMPO VAZIO");
        }else{
         
            cozinheiro cozinheiro_tela = new cozinheiro(jTextFieldnn.getText(), jTextFieldnF.getText(), jTextFieldData.getText());
        
            try {
                //categoriabanco precisa da conexao com o banco pra inserir
                Connection conexao = new Conexao().getConnection();
                CozinheiroDAO cozinheirobanco = new CozinheiroDAO(conexao);
            
                cozinheirobanco.update(cozinheiro_tela);
                JOptionPane.showMessageDialog(null,"Cozinheiro atualizado com sucesso!!!");
                readTable();
                jTextFieldnF.setText("");
                jTextFieldnn.setText("");
                jTextFieldData.setText("");
               

            } catch (SQLException ex) {
                Logger.getLogger(cozinheiroView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_ATUALIZARActionPerformed

    private void jTextFieldnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldnnActionPerformed

    private void DELETARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETARActionPerformed
        // TODO add your handling code here:
        if(jTextFieldnn.getText().isEmpty() || jTextFieldnF.getText().isEmpty() || jTextFieldData.getText().isEmpty() ){
             JOptionPane.showMessageDialog(null,"CAMPO VAZIO");
        }else{
         
            cozinheiro cozinheiro_tela = new cozinheiro(jTextFieldnn.getText(), jTextFieldnF.getText(), jTextFieldData.getText());
        
            try {
                //categoriabanco precisa da conexao com o banco pra inserir
                Connection conexao = new Conexao().getConnection();
                CozinheiroDAO cozinheirobanco = new CozinheiroDAO(conexao);
            
                cozinheirobanco.delete(cozinheiro_tela);
                JOptionPane.showMessageDialog(null,"Cozinheiro removido com sucesso!!!");
                readTable();
                jTextFieldnF.setText("");
                jTextFieldnn.setText("");
                jTextFieldData.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(cozinheiroView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_DELETARActionPerformed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        if(jTextFieldBusca.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"CAMPO VAZIO");
        }
        else{
           try {
            readDesc(jTextFieldBusca.getText());
        } catch (SQLException ex) {
            Logger.getLogger(cozinheiroView.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
        
    }//GEN-LAST:event_jButtonBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cozinheiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cozinheiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cozinheiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cozinheiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cozinheiroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATUALIZAR;
    private javax.swing.JButton CADASTRAR;
    private javax.swing.JButton DELETAR;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldnF;
    private javax.swing.JTextField jTextFieldnn;
    // End of variables declaration//GEN-END:variables

}
