/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

/**
 *
 * @author Matheus
 */
public class MenuView extends javax.swing.JFrame {

    /** Creates new form MenuView */
    public MenuView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCAT = new javax.swing.JButton();
        jButtonCOZ = new javax.swing.JButton();
        jButtonDE = new javax.swing.JButton();
        jButtonEDI = new javax.swing.JButton();
        jButtonING = new javax.swing.JButton();
        jButtonLIV = new javax.swing.JButton();
        jButtonRES = new javax.swing.JButton();
        jButtonRE = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jButtonCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("MENU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FAVOR ESCOLHA UMA OPÇÃO");

        jButtonCAT.setText("Categoria");
        jButtonCAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCATActionPerformed(evt);
            }
        });

        jButtonCOZ.setText("Cozinheiros");
        jButtonCOZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOZActionPerformed(evt);
            }
        });

        jButtonDE.setText("Degustadores");
        jButtonDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDEActionPerformed(evt);
            }
        });

        jButtonEDI.setText("Editores");
        jButtonEDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDIActionPerformed(evt);
            }
        });

        jButtonING.setText("Ingredientes");
        jButtonING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonINGActionPerformed(evt);
            }
        });

        jButtonLIV.setText("Livros");
        jButtonLIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLIVActionPerformed(evt);
            }
        });

        jButtonRES.setText("Restaurantes");
        jButtonRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESActionPerformed(evt);
            }
        });

        jButtonRE.setText("Receitas");
        jButtonRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREActionPerformed(evt);
            }
        });

        jButtonRelatorio.setText("Relatorio_Cozinheiro");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });

        jButtonCard.setText("CARDÁPIO");
        jButtonCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRES)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonCAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCOZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonLIV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonCard)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEDI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButtonRelatorio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCAT)
                    .addComponent(jButtonDE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCOZ)
                    .addComponent(jButtonEDI)
                    .addComponent(jButtonCard))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonING)
                    .addComponent(jButtonLIV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRES)
                    .addComponent(jButtonRE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelatorio)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCATActionPerformed
        categoriaView TelaCat = new categoriaView();
        TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonCATActionPerformed

    private void jButtonCOZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOZActionPerformed
        cozinheiroView TelaCat = new cozinheiroView();
        TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonCOZActionPerformed

    private void jButtonDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDEActionPerformed
        degustadoresView TelaCat = new degustadoresView();
        TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonDEActionPerformed

    private void jButtonEDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDIActionPerformed
        editoresView TelaCat = new editoresView();
        TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonEDIActionPerformed

    private void jButtonINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonINGActionPerformed
        ingredientesView TelaCat = new ingredientesView();
        TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonINGActionPerformed

    private void jButtonLIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLIVActionPerformed
        livrosView TelaCat = new livrosView ();
        TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonLIVActionPerformed

    private void jButtonRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESActionPerformed
       restaurantesView TelaCat = new restaurantesView ();
       TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonRESActionPerformed

    private void jButtonREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREActionPerformed
       receitasView TelaCat = new receitasView ();
       TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonREActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
       relatorioView telinha = new relatorioView ();
       telinha.setVisible(true);
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jButtonCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCardActionPerformed
       Cardapio TelaCat = new Cardapio();
       TelaCat.setVisible(true);
    }//GEN-LAST:event_jButtonCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCAT;
    private javax.swing.JButton jButtonCOZ;
    private javax.swing.JButton jButtonCard;
    private javax.swing.JButton jButtonDE;
    private javax.swing.JButton jButtonEDI;
    private javax.swing.JButton jButtonING;
    private javax.swing.JButton jButtonLIV;
    private javax.swing.JButton jButtonRE;
    private javax.swing.JButton jButtonRES;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
